# Generated by Django 4.2.30 on 2026-07-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('drink_type', models.CharField(choices=[('beer', 'ビール'), ('sake', '日本酒'), ('shochu', '焼酎'), ('wine', 'ワイン'), ('whisky', 'ウイスキー'), ('cocktail', 'カクテル'), ('other', 'その他')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
